### ISSUE TITLE
structured formatted data

### ISSUE THREAD

**Issue by jjl** [doy/vt100-rust#1]
Hi,

Great module, and nice to see someone I recognise from the perl community working with rust :)

For my use case (a graphical terminal emulator), it would be handy to get the formatting information back in some structured way rather than parsing the ansi-escaped output again and translating it into this. Is this something you have planned or do you have advice for how I might go about it?

Best,
James

**Comment by doy** [comment]
yeah, this is already doable - something like ```rust
let screen = parser.screen();
let (rows, cols) = screen.size();
for row in 0..rows {
    for col in 0..cols {
        let cell = screen.cell(row, col);
        your_thing_to_render_cell(
            cell.contents(),
            cell.fgcolor(),
            cell.bgcolor(),
            // ...etc
        );
    }
}
```

is there something i can do to make this more clear?

**Comment by jjl** [comment]
That probably should have occurred to me to be quite honest. Maybe pasting that into the docs would be helpful, I guess?

Thanks,
James
